baseurl = "https://brendanr.net"
languageCode = "en"
title = "Brendan Roy"
theme = "hemingway2"
copyright = "&copy; <a href=\"https://github.com/bmon\">Brendan Roy</a> 2017"
googleAnalytics = ""
description = "Full Stack Developer"

[taxonomies]
tag = "tags"
category = "categories"

[params]

[params.highlight]
style = "github"
languages = ["go", "dockerfile"]

[[params.social]]
url = "https://github.com/bmon"
fa_icon = "fa-github"

[[params.social]]
url = "https://www.linkedin.com/in/brendan-roy/"
fa_icon = "fa-linkedin"

[[params.social]]
url = "mailto:br3ndanr@gmail.com"
fa_icon = "fa-envelope"

[[params.social]]
url = "/index.xml"
fa_icon = "fa-rss"

[[menu.main]]
name = "Home"
weight = -110
identifier = "home"
url = "/"
[[menu.main]]
name = "Resume"
weight = -90
identifier = "resume"
url = "/doc/resume.pdf"
